debug: true
server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: tomcat
#    key-password: password
#  port: 8443
#  tomcat:
#    accesslog:
#      suffix: .log
#      enabled: true
#      prefix: access_log
#      file-date-format: .yyyy-MM-dd

auth0:
  audience: ${AUDIENCE}

azure:
  keyvault:
    enabled: true
    uri: ${AZURE_URI}
    client-id: ${AZURE_ID}
    client-secret: ${AZURE_SECRET}

spring:
  main:
    banner-mode=off:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${I_URI}

  profiles:
    active: dev

  h2:
    console:
      enabled=true:


  jpa:
    show-sql=true:


  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

    jpa:
      repositories:
        bootstrap-mode=default:


  datasource:
    url=jdbc:h2:mem:testdb:


  messages:
    basename=messages:

  spring:
    jpa:
      show-sql=true:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework: ERROR
    com.handoferis: DEBUG
    org.hibernate: ERROR

