debug: true
server:
  port:8080

auth0:
  audience: https://info.handoferis.us



spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-3c9hn7ky.us.auth0.com/


  h2:
    console:
      enabled=true:


  jpa:
    show-sql=true:


  data:
    jpa:
      repositories:
        bootstrap-mode=default:


  datasource:
    url=jdbc:h2:mem:testdb:


  messages:
    basename=messages:


#  jackson:
#    serialization:
#      write-date-keys-as-timestamps=false:

#  logging.level.org.springframework = info